DSA TASK/SCRUM-6/Find the Longest Consecutive Sequence in an Unsorted Array.py

this is the program to Find the Longest Consecutive Sequence in an Unsorted Array

Find the Longest Consecutive Sequence in an Unsorted Array

---

DSA TASK/SCRUM-35/Perfect Numbers.py

this is the program to find perfect number

add perfect number

---

DSA TASK/SCRUM-1/palindrome.py

Scrum 1 palindrome check

---

DSA TASK/SCRUM-13/Word Break II.py

this is program to find word break

SCRUM-13   Word Break II

---

DSA TASK/SCRUM-13/House Robber.java
DSA TASK/SCRUM-18/Longest string.java

This is the code to Longest String

Scrum 18 longest string

---

DSA TASK/SCRUM-13/House Robber.java

SCRUM-13-house robber

---

DSA TASK/SCRUM-22/Search insert position.py

This  is the program to find the search insert position

SCRUM-22 Search insert position

---

DSA TASK/SCRUM-33/Implement two stacks in an array.py
DSA TASK/SCRUM-34/Print all Divisors of a number.py
DSA TASK/SCRUM-36/ArrayChange.py

this is the program of array change

Scrum 36 array change

---

DSA TASK/SCRUM-33/Implement two stacks in an array.py
DSA TASK/SCRUM-34/Print all Divisors of a number.py

this is the program to print all divisors of  a number

Scrum 34 print all divisors of a number

---

DSA TASK/SCRUM-13/House Robber.java
DSA TASK/SCRUM-18/Longest string.java
DSA TASK/SCRUM-23/firstDigit.java

This is the code for First Digit

Scrum 23 first digit

---

DSA TASK/SCRUM-13/House Robber.java
DSA TASK/SCRUM-18/Longest string.java
DSA TASK/SCRUM-23/firstDigit.java
DSA TASK/SCRUM-28/ArrayReplace.java

This is the code for array replace.

Scrum 28 array replace

---

DSA TASK/SCRUM-13/House Robber.java
DSA TASK/SCRUM-18/Longest string.java
DSA TASK/SCRUM-23/firstDigit.java
DSA TASK/SCRUM-28/ArrayReplace.java
DSA TASK/SCRUM-31/Print Pattern.java

This is the code for Print pattern

Scrum 31 print pattern

---

DSA TASK/SCRUM-13/House Robber.java
DSA TASK/SCRUM-18/Longest string.java
DSA TASK/SCRUM-23/firstDigit.java
DSA TASK/SCRUM-28/ArrayReplace.java
DSA TASK/SCRUM-31/Print Pattern.java
DSA TASK/SCRUM-32/BuildPalindrome.java

This is code for Build Palindrome.

Scrum 32 build palindrome

---

DSA TASK/SCRUM-12/House Robber.java

This is the code for House Robber

Scrum-12-house robber

---

DSA TASK/SCRUM-1/palindromecheck.py

SCRUM-1-palindromecheck.py

---

DSA TASK/SCRUM-37/majorityelement.py

SCRUM-37 majorityelement.py

---

DSA TASK/SCRUM-17/permutations.py

Scrum-17 permutations.py

---

DSA TASK/SCRUM-35/Perfect Numbers.py
DSA TASK/SCRUM-6/Find the Longest Consecutive Sequence in an Unsorted Array.py

this is the program to find perfect numbers

SCRUM-35 perfect numbers

---

DSA TASK/SCRUM-6/Find the Longest Consecutive Sequence in an Unsorted Array.py

this is the program to find consecutive sequence in an unsorted array

SCRUM-6 -Find the Longest Consecutive Sequence in an Unsorted Array

---

DSA TASK/SCRUM-26/kth-element-of-2sorted-arrays.cpp

SCRUM-26 2 pointers approach

---

DSA TASK/SCRUM-19/banana.py

This is the program to find the koko eating bananas

koko eating bananas

---

DSA TASK/SCRUM-21/divisor.py

This is the program to find the smallest divisor given a threshold

Find the smallest divisor given a threshold

---

DSA TASK/SCRUM-3/balance.py

This is the program to find the balance the scales

Can You Balance the Scales?
